name: Embed GitHub Snippets

on:
  push:
    branches: [ "**" ]  # Run on any branch
  workflow_dispatch:

jobs:
  embed-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to commit to current branch

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install axios @octokit/rest

      - name: Embed GitHub code into Markdown
        run: node .github/scripts/embed-github-snippets.js

      - name: Commit .md file changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add '*.md'
          git diff --staged --quiet || git commit -m "Embed GitHub code snippets into Markdown"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
